### ISSUE TITLE
Adding sites

### ISSUE THREAD

**Issue by ysqander** [Webflow-Examples/Hybrid-App-Example#3]
Once you get both apps running and go to localhost/1337, then give the openaitoken, how do you add sites? I do not see any sites. and when I authorize through the app on localhost:3001, nothing happens. 

The example could do with a bit more guidance on the elements and how they interact with the new API!

**Comment by Mansi1662** [comment]
hey!! how did you add the site?

**Comment by Mansi1662** [comment]
> Once you get both apps running and go to localhost/1337, then give the openaitoken, how do you add sites? I do not see any sites. and when I authorize through the app on localhost:3001, nothing happens.
> 
> The example could do with a bit more guidance on the elements and how they interact with the new API!

hhhh

**Comment by Mansi1662** [comment]
> Once you get both apps running and go to localhost/1337, then give the openaitoken, how do you add sites? I do not see any sites. and when I authorize through the app on localhost:3001, nothing happens.
> 
> The example could do with a bit more guidance on the elements and how they interact with the new API!

hey!! how did you add the site???? can you please guide me and also how to get NEXT_PUBLIC_BACKEND_URL in designer extension?

**Comment by gate3** [comment]
> > Once you get both apps running and go to localhost/1337, then give the openaitoken, how do you add sites? I do not see any sites. and when I authorize through the app on localhost:3001, nothing happens.
> > The example could do with a bit more guidance on the elements and how they interact with the new API!
> 
> hey!! how did you add the site???? can you please guide me and also how to get NEXT_PUBLIC_BACKEND_URL in designer extension?

- To add sites you should visit the url for the backend, I believe that is [](http://localhost:3001)
- Also the `NEXT_PUBLIC_BACKEND_URL` is an environment variable for the designer extension app. You need to have a .env file present in the designer extension and you can add a value to it like this 

`NEXT_PUBLIC_BACKEND_URL=http://localhost:3001/`

**Comment by lunchpaillola** [comment]
And if you're running it in GitHub codespaces your NEXT_PUBLIC_BACKEND_URL will look like this 

https://curly-train-5rg69pjrrp9f4v6v-3001.app.github.dev
